// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr-XqAPCkVxrOzOFeKhT19u9ck_xemBH8',
    appId: '1:450323966838:web:5a20e2301b32d0c1f2a857',
    messagingSenderId: '450323966838',
    projectId: 'todoapp-7bca8',
    authDomain: 'todoapp-7bca8.firebaseapp.com',
    storageBucket: 'todoapp-7bca8.appspot.com',
    measurementId: 'G-9LS181BCZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYYXeqeyT_-TVR0BdlHkX7_5F8v0K4LBY',
    appId: '1:450323966838:android:38584b2ad467919ef2a857',
    messagingSenderId: '450323966838',
    projectId: 'todoapp-7bca8',
    storageBucket: 'todoapp-7bca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCJnRlGAk7Ky9MwXS2Y0PetiGAz82n2I4',
    appId: '1:450323966838:ios:119e71ae99177f5ff2a857',
    messagingSenderId: '450323966838',
    projectId: 'todoapp-7bca8',
    storageBucket: 'todoapp-7bca8.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCJnRlGAk7Ky9MwXS2Y0PetiGAz82n2I4',
    appId: '1:450323966838:ios:119e71ae99177f5ff2a857',
    messagingSenderId: '450323966838',
    projectId: 'todoapp-7bca8',
    storageBucket: 'todoapp-7bca8.appspot.com',
    iosBundleId: 'com.example.todoapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr-XqAPCkVxrOzOFeKhT19u9ck_xemBH8',
    appId: '1:450323966838:web:9dee130e45eb13adf2a857',
    messagingSenderId: '450323966838',
    projectId: 'todoapp-7bca8',
    authDomain: 'todoapp-7bca8.firebaseapp.com',
    storageBucket: 'todoapp-7bca8.appspot.com',
    measurementId: 'G-1WD5PK4MS7',
  );
}
